"""
Nugen AI Prompt Construction Module.
Builds strict system and user prompts enforcing all domain validation rules and hallucination guards.
"""
import json
from typing import Any, Dict, Optional


NUGEN_SYSTEM_PROMPT = """You are an itinerary validation and enhancement AI (Nugen AI).
You are NOT the primary itinerary generator.
The supplied itinerary was generated by an existing ML recommendation and itinerary system.

CRITICAL RULES:
1. You MUST preserve that itinerary's factual data.
2. You MUST NOT:
   - replace recommendations
   - remove or reorder any activities
   - generate a completely new itinerary
   - invent missing factual information
   - invent prices or discounts
   - invent ratings or reviews
   - invent coordinates or addresses
   - invent opening or closing hours
   - invent travel times or distances
   - invent booking availability or policies
3. If information does not exist in the supplied itinerary data, explicitly state: "Could not be verified from the supplied itinerary data".
4. Clearly distinguish:
   - Confirmed facts directly provided by the itinerary
   - Advisory suggestions and tips generated by Nugen AI
5. Return ONLY a single valid JSON object strictly matching the schema below. No markdown formatting, no conversational text outside JSON.

VALIDATION DOMAIN RULES:
- RULE 1 (Budget Validation): Compare total itinerary cost against user budget. If cost > budget, status="warning" or "fail", explain the discrepancy, and suggest practical saving tips. Do NOT alter itinerary prices.
- RULE 2 (Available Time Validation): Check if total duration realistically fits inside user available time limit. Flag tight schedules.
- RULE 3 (Selected Place Count): Verify if the number of selected places matches scheduled experiences. If any were skipped or missing, explain why without replacing recommendations.
- RULE 4 (Interest Personalization): Validate whether scheduled activities align with user's selected interests (e.g. food, culture, adventure, nature, heritage).
- RULE 5 (Group Type Personalization): Provide practical group-specific considerations (e.g. Solo, Couple, Family with children, Friends) without fabricating venue policies.
- RULE 6 (Detect Rushed Scheduling): Detect tight transits (<5 min buffer or overlapping activities). If travel time is missing, explicitly note that travel time could not be verified.

REQUIRED JSON OUTPUT SCHEMA:
{
  "validation": {
    "budget": { "status": "pass|warning|fail|unknown", "message": "..." },
    "available_time": { "status": "pass|warning|fail|unknown", "message": "..." },
    "selected_place_count": { "status": "pass|warning|fail|unknown", "message": "..." },
    "interests": { "status": "pass|warning|fail|unknown", "message": "..." },
    "group_type": { "status": "pass|warning|fail|unknown", "message": "..." },
    "schedule": { "status": "pass|warning|fail|unknown", "message": "..." }
  },
  "issues": [
    {
      "type": "budget_exceeded|schedule_conflict|missing_selection|time_overflow|rushed_transit",
      "severity": "low|medium|high",
      "message": "...",
      "affected_items": ["..."]
    }
  ],
  "enhancements": [
    {
      "type": "practical_tip|pacing|convenience",
      "suggestion": "...",
      "reason": "...",
      "based_on": "..."
    }
  ],
  "personalized_tips": [
    {
      "tip": "...",
      "reason": "..."
    }
  ],
  "final_recommendations": [
    {
      "type": "advisory",
      "recommendation": "...",
      "reason": "...",
      "source": "nugen"
    }
  ]
}
"""


def build_nugen_payload(
    user_constraints: Dict[str, Any],
    generated_itinerary: Dict[str, Any],
    weather: Optional[Dict[str, Any]] = None,
) -> Dict[str, Any]:
    """
    Construct standardized payload sent to Nugen AI enhancement layer.
    """
    payload = {
        "user_constraints": {
            "budget": user_constraints.get("budget") or user_constraints.get("budget_inr"),
            "available_time_hours": user_constraints.get("available_time_hours") or user_constraints.get("duration_hours"),
            "traveler_count": user_constraints.get("traveler_count", 1),
            "group_type": user_constraints.get("group_type") or user_constraints.get("traveler_type") or "Solo",
            "interests": user_constraints.get("interests", []),
            "selected_places": user_constraints.get("selected_places") or user_constraints.get("selected_experience_ids", []),
            "destination": user_constraints.get("destination", ""),
        },
        "generated_itinerary": {
            "destination": generated_itinerary.get("destination", ""),
            "trip_date": generated_itinerary.get("trip_date", ""),
            "start_time": generated_itinerary.get("start_time", ""),
            "end_time": generated_itinerary.get("end_time", ""),
            "total_duration_minutes": generated_itinerary.get("total_duration_minutes", 0),
            "total_duration_formatted": generated_itinerary.get("total_duration_formatted", ""),
            "total_cost": generated_itinerary.get("total_cost", 0.0),
            "total_experience_cost": generated_itinerary.get("total_experience_cost", 0.0),
            "estimated_transport_cost": generated_itinerary.get("estimated_transport_cost", 0.0),
            "budget": generated_itinerary.get("budget", 0.0),
            "budget_exceeded": generated_itinerary.get("budget_exceeded", False),
            "scheduled_experiences": [
                {
                    "sequence": exp.get("sequence"),
                    "experience_id": exp.get("experience_id"),
                    "name": exp.get("experience_name") or exp.get("name"),
                    "category": exp.get("category"),
                    "sub_category": exp.get("sub_category"),
                    "location": exp.get("location"),
                    "start_time": exp.get("start_time"),
                    "end_time": exp.get("end_time"),
                    "duration_minutes": exp.get("duration_minutes"),
                    "price": exp.get("price") or exp.get("price_inr", 0.0),
                    "travel_to_next_minutes": exp.get("travel_to_next_minutes", 0),
                    "travel_to_next_distance_km": exp.get("travel_to_next_distance_km", 0.0),
                    "indoor_outdoor": exp.get("indoor_outdoor"),
                    "booking_required": exp.get("booking_required"),
                }
                for exp in (generated_itinerary.get("scheduled_experiences") or generated_itinerary.get("itinerary") or [])
            ],
            "skipped_experiences": generated_itinerary.get("skipped_experiences", []),
        },
    }

    if weather:
        payload["weather"] = {
            "condition": weather.get("condition"),
            "temperature": weather.get("temperature"),
            "rainfall_mm": weather.get("rainfall_mm"),
            "humidity_pct": weather.get("humidity_pct"),
            "wind_speed_kmh": weather.get("wind_speed_kmh"),
        }

    return payload


def build_nugen_user_prompt(payload: Dict[str, Any]) -> str:
    """
    Format the user prompt with exact JSON payload for Nugen AI.
    """
    return (
        "Analyze and validate the following generated itinerary against the user constraints. "
        "Enforce all validation rules, verify no factual data is invented, clearly separate facts from suggestions, "
        "and return the strictly formatted JSON validation result.\n\n"
        f"{json.dumps(payload, indent=2, default=str)}"
    )
